merge minimo

diff --git a/archiso/airootfs/usr/bin/al-conky-pipemenu b/archiso/airootfs/usr/bin/al-conky-pipemenu
--- a/archiso/airootfs/usr/bin/al-conky-pipemenu
+++ b/archiso/airootfs/usr/bin/al-conky-pipemenu
@@ -38,7 +38,7 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
+AL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 
 CONKYDEFAULT="$HOME/.conkyrc"
 CONKYPATH="$HOME/.config/conky"
@@ -48,8 +48,8 @@ CZEN="al-conkyzen"
 CSESSION="al-conky-session"
 HELPFILE="/usr/share/archlabs/docs/helpfile-conkyzen.txt"
 
-if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
-    echo "Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$AL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo "Error: Failed to source al-include.cfg in $AL_COMMON_LIBDIR" >&2
     exit 1
 fi
 if [ ! -e "$CSESSIONFILE" ] 2> /dev/null ; then
@@ -109,14 +109,14 @@ loadPinMenu(){
 }
 
 loadEditMenu(){
-    menuItem "Default conkyrc" "geany $CONKYDEFAULT"
+    menuItem "Default conkyrc" "exo-open $CONKYDEFAULT"
     if [[ $(pidof conky) ]];then
         menuSubmenu "RunningConky" "Running Conkys"
         while read -r session ;do  # get running conkys from sessionfile
             [[ -z $session ]] && continue
             CPATH=$(echo "$session" | awk '{print $3}')
             CONKY=$(echo "$CPATH" | awk -F"/" '{print $(NF-1)"/"$NF }')
-            menuItem "$CONKY" "geany $CPATH"
+            menuItem "$CONKY" "exo-open $CPATH"
         done < "$CSESSIONFILE"
         menuSubmenuEnd
     else
@@ -136,12 +136,11 @@ getConkys(){
 }
 
 checkHelpfile(){
-    DLG="yad --text-info --center --borders=20 \
-    --title='ARCHLabs Conky Manager Help' \
-    --window-icon=distributor-logo-bunsenlabs \
-    --filename=$HELPFILE --fontname=Monospace \
+    DLG="zenity --text-info \
+    --title='ArchLabs Conky Manager Help' \
+    --filename=$HELPFILE \
     --width=650 --height=700 \
-    --button=OK:0"
+    --ok-label=OK"
     if [[ -e $HELPFILE ]];then
         menuItem "Conky Manager Help" "$DLG"
     fi
diff --git a/archiso/airootfs/usr/bin/al-help-pipemenu b/archiso/airootfs/usr/bin/al-help-pipemenu
--- a/archiso/airootfs/usr/bin/al-help-pipemenu
+++ b/archiso/airootfs/usr/bin/al-help-pipemenu
@@ -1,6 +1,7 @@
 #!/bin/bash
 #    al-help-pipemenu - an Openbox pipemenu for displaying help files
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
+#    Borrowed with love by the ArchLabs Boys.
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -15,7 +16,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-#	Renamed for ARCHLabs
+#	Renamed for Archlabs
 
 HELP='    al-help-pipemenu an Openbox Pipe Menu for displaying help files
     It should normally be called from an openbox menu.
@@ -38,69 +39,76 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
+AL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 
-if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$AL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $AL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
 menuStart
-menuSeparator 'Online Help'
+menuSeparator 'ArchLabs Linux Online'
 menuSeparator
-menuItem 'ARCHLabs Forum Homepage' 'chromium "http://archlabs.prophpbb.com/"'
-menuItem 'Forum Basic Help & Support' 'chromium "http://archlabs.prophpbb.com/forum7.html"'
-menuItem 'Scripts, Tutorials & Tips' 'chromium "https://bbs.archlinux.org/viewforum.php?id=33"'
+menuItem 'ArchLabs Homepage' 'exo-open "https://archlabsblog.wordpress.com/"'
+menuItem 'ArchLabs Reddit' 'exo-open "https://www.reddit.com/r/ArchLabsLinux/"'
+menuItem 'ArchLabs Medium' 'exo-open "https://medium.com/@archlabslinux"'
+menuItem 'ArchLabs Forum' 'exo-open "http://archlabs.prophpbb.com/"'
+menuItem 'ArchLabs Google+' 'exo-open "https://plus.google.com/u/0/communities/111177505820810068511"'
 
+menuSeparator 'ArchLabs Linux Help'
 menuSeparator
-
-menuItem 'Arch Wiki' 'chromium "https://wiki.archlinux.org/index.php/Table_of_contents"'
+menuItem 'Forum Basic Help & Support' 'exo-open "http://archlabs.prophpbb.com/forum7.html"'
+menuItem 'Scripts, Tutorials & Tips' 'exo-open "https://bbs.archlinux.org/viewforum.php?id=33"'
 
 menuSeparator
 
 menuSubmenu 'OpenboxWWW' 'Openbox'
 menuSubmenu 'ObWWW' 'Openbox Website'
-menuItem 'Openbox Homepage' 'chromium "http://openbox.org/"'
-menuItem 'Openbox Getting Started' 'chromium "http://openbox.org/wiki/Help:Getting_started"'
-menuItem 'Openbox Documentation' 'chromium "http://openbox.org/wiki/Help:Contents"'
-menuItem 'Openbox FAQs' 'chromium "http://openbox.org/wiki/Help:FAQ"'
+menuItem 'Openbox Homepage' 'exo-open "http://openbox.org/"'
+menuItem 'Openbox Getting Started' 'exo-open "http://openbox.org/wiki/Help:Getting_started"'
+menuItem 'Openbox Documentation' 'exo-open "http://openbox.org/wiki/Help:Contents"'
+menuItem 'Openbox FAQs' 'exo-open "http://openbox.org/wiki/Help:FAQ"'
 menuSubmenuEnd
-menuItem 'ArchWiki Openbox Guide' 'chromium "http://wiki.archlinux.org/index.php/Openbox"'
-menuItem 'Debian Wiki Openbox Guide' 'chromium "https://wiki.debian.org/Openbox"'
-menuItem 'Urukramas Openbox Guide' 'chromium "https://urukrama.wordpress.com/openbox-faq/"'
-menuItem 'Openbox Reddit' 'chromium "https://www.reddit.com/r/openbox/"'
+menuItem 'Arch Wiki Openbox Guide' 'exo-open "http://wiki.archlinux.org/index.php/Openbox"'
+menuItem 'Debian Wiki Openbox Guide' 'exo-open "https://wiki.debian.org/Openbox"'
+menuItem 'Urukramas Openbox Guide' 'exo-open "https://urukrama.wordpress.com/openbox-faq/"'
+menuItem 'Openbox Reddit' 'exo-open "https://www.reddit.com/r/openbox/"'
 menuSubmenuEnd
 
 menuSubmenu 'Tint2WWW' 'Tint2'
-menuItem 'Tint2 Wiki: FAQ' 'chromium "https://gitlab.com/o9000/tint2/wikis/FAQ"'
-menuItem 'Tint2 Wiki: Configuration' 'chromium "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
-menuItem 'Tint2 Forum Thread' 'chromium "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
-menuItem 'Tint2 man page' 'urxvt -T "Tint2 man page" -e man tint2'
+menuItem 'Tint2 Wiki: FAQ' 'exo-open "https://gitlab.com/o9000/tint2/wikis/FAQ"'
+menuItem 'Tint2 Wiki: Configuration' 'exo-open "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
+menuItem 'Tint2 Forum Thread' 'exo-open "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
+menuItem 'Tint2 Man Pages' 'urxvt -T "Tint2 man page" -e man tint2'
 menuSubmenuEnd
 
 menuSubmenu 'ConkyWWW' 'Conky'
-menuItem 'Conky Wiki' 'chromium "https://github.com/brndnmtthws/conky/wiki"'
-menuItem 'Conky Archive' 'chromium "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
-menuItem 'Conky Reddit' 'chromium "https://www.reddit.com/r/conky/"'
-menuItem 'Conky man pages' 'urxvt -T "Conky man page" -e man conky'
+menuItem 'Conky Wiki' 'exo-open "https://github.com/brndnmtthws/conky/wiki"'
+menuItem 'Conky Archive' 'exo-open "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
+menuItem 'Conky Reddit' 'exo-open "https://www.reddit.com/r/conky/"'
+menuItem 'Conky Man Pages' 'urxvt -T "Conky man page" -e man conky'
 menuSubmenuEnd
 menuSeparator
 
 menuSubmenu 'ThemesWWW' 'Theme Resources'
-menuItem 'Bunsenlabs on DeviantArt' 'chromium "http://bunsenlabs.deviantart.com/"'
-menuItem 'Eye Candy Linux DeviantArt' 'chromium "http://eye-candy-linux.deviantart.com/"'
-menuItem 'Box-Look.org' 'chromium "http://www.box-look.org"'
-menuItem 'gnome-look.org' 'chromium "http://gnome-look.org/"'
-menuItem 'Eye Candy Linux Google+' 'chromium "https://plus.google.com/u/0/communities/104794997718869399105"'
-menuItem 'UnixPorn' 'chromium "https://www.reddit.com/r/unixporn/"'
-menuItem 'nixers.net' 'chromium "http://nixers.net/"'
+menuItem 'Bunsenlabs on DeviantArt' 'exo-open "http://bunsenlabs.deviantart.com/"'
+menuItem 'Eye Candy Linux DeviantArt' 'exo-open "http://eye-candy-linux.deviantart.com/"'
+menuItem 'Box-Look.org' 'exo-open "http://www.box-look.org"'
+menuItem 'Gnome-Look.org' 'exo-open "http://gnome-look.org/"'
+menuItem 'Eye Candy Linux Google+' 'exo-open "https://plus.google.com/u/0/communities/104794997718869399105"'
+menuItem 'UnixPorn' 'exo-open "https://www.reddit.com/r/unixporn/"'
+menuItem 'nixers.net' 'exo-open "http://nixers.net/"'
 menuSubmenuEnd
 
-menuSeparator 'man pages'
+menuSeparator 'Man Pages'
 menuItem 'Compositor' 'urxvt -T "Compositor man page" -e man compton'
-menuItem 'dmenu' 'urxvt -T "dmenu man page" -e man dmenu'
-menuItem 'gmrun' 'urxvt -T "gmrun man page" -e man gmrun'
-menuItem 'xrandr' 'urxvt -T "xrandr man page" -e man xrandr'
+menuItem 'Dmenu' 'urxvt -T "dmenu man page" -e man dmenu'
+menuItem 'Xrandr' 'urxvt -T "xrandr man page" -e man xrandr'
+menuItem 'Yad' 'urxvt -T "yad man page" -e man yad'
 
+menuSeparator 'Wikis'
+menuItem 'Arch Wiki' 'exo-open "https://wiki.archlinux.org/index.php/Table_of_contents"'
+menuItem 'Termite' 'exo-open "https://wiki.archlinux.org/index.php/termite"'
 
 menuEnd
+
diff --git a/archiso/airootfs/usr/bin/al-kb-pipemenu b/archiso/airootfs/usr/bin/al-kb-pipemenu
--- a/archiso/airootfs/usr/bin/al-kb-pipemenu
+++ b/archiso/airootfs/usr/bin/al-kb-pipemenu
@@ -20,7 +20,7 @@
 
 # al-kb is used to parse rc.xml and send the output to a textfile
 
-#	Renamed for ARCHLabs
+#	Renamed for ArchLabs
 
 HELP='    al-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
     It should normally be called from an openbox menu.
@@ -49,21 +49,21 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR="/usr/lib/archlabs/common"
+AL_COMMON_LIBDIR="/usr/lib/archlabs/common"
 USR_CFG_DIR="$HOME/.config/openbox"
 KBSCRIPT="al-kb"
 RCPATH="$USR_CFG_DIR/rc.xml"
 KBTEXT="$USR_CFG_DIR/kbinds.txt"
 
-if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate al-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$AL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate al-include.cfg in $AL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
 # test if al-kb exists in path
 if ! type "$KBSCRIPT" &> /dev/null;then
     menuStart
-    menuSeparator "$KBSCRIPT is not available. Try installing ARCHLabs-utilities."
+    menuSeparator "$KBSCRIPT is not available. Try installing ArchLabs-utilities."
     menuEnd
     exit 1
 fi
@@ -73,7 +73,7 @@ if [[ $1 = '--rcedit' ]];then # "Backup & Edit rc.xml" is chosen in menu
     NOW=$(date +"%Y%m%d-%H%M")
     RCBKP="$RCPATH.$NOW"
     cp "$RCPATH" "$RCBKP"
-    geany "$RCPATH"        # open rc.xml in default editor
+    exo-open "$RCPATH"        # open rc.xml in default editor
     exit
 fi
 
@@ -105,7 +105,7 @@ fi
 menuStart
     menuItem "Backup and Edit rc.xml" "al-kb-pipemenu --rcedit"
     menuSeparator
-    menuItem "Display Keybinds in new window" "al-kb --gui"
+    menuItem "Display Keybinds in window" "python2 al-kb --gui"
     echo '        <menu execute="al-kb-pipemenu --keybinds" id="Display keybinds" label="Display Keybinds in menu"/>'
 menuEnd
 
